### ISSUE TITLE
Score calculation

### ISSUE THREAD

**Issue by iakanoe** [sergiuwd/Processing-2048#2]
Re-uploaded, submitted by mistake before finishing the text.

Is the score well calculated? Dan said in his CC that it has to add to the score every time a "combination" is made.
In this code, for example, when a game is started, the score will be some even number between 2 and 8. What Dan said is that the score must start being 0 and add as the player moves.

**Comment by sergiuwd** [comment]
Yeah, my bad, I'll fix it.

**Comment by sergiuwd** [comment]
@iakanoe fixed.
